STORY_EVENTS = [
    # ─────────────────────────────────────────────────────────────────────────
    # EVENT 1 — Match Day Begins
    # ─────────────────────────────────────────────────────────────────────────
    {
        "time": 0,
        "id": "event_match_start",
        "title": "Match Day Begins",
        "description": "Stadium opening. All systems nominal. Fans beginning to arrive.",
        "type": "info",
        "zone_densities": {
            "north_gate_a":   0.30,
            "south_gate_b":   0.28,
            "east_gate_c":    0.25,
            "west_gate_d":    0.22,
            "field_level":    0.35,
            "lower_bowl":     0.40,
            "upper_bowl":     0.30,
            "concourse_main": 0.20,
        },
        "zone_risks": {
            "north_gate_a":   "safe",
            "south_gate_b":   "safe",
            "east_gate_c":    "safe",
            "west_gate_d":    "safe",
            "field_level":    "safe",
            "lower_bowl":     "safe",
            "upper_bowl":     "safe",
            "concourse_main": "safe",
        },
        "risk_level": 15,
        "agent_states": {
            "crowd":         {"status": "monitoring", "thinking": "All zones within safe parameters. Monitoring fan arrival rates.", "confidence": 82},
            "transport":     {"status": "monitoring", "thinking": "Metro Line 1 and 2 nominal. Bus arrivals on schedule.", "confidence": 80},
            "security":      {"status": "monitoring", "thinking": "All 847 security personnel checked in. No anomalies detected.", "confidence": 85},
            "medical":       {"status": "monitoring", "thinking": "All 12 medical stations staffed. Equipment checked.", "confidence": 90},
            "accessibility": {"status": "monitoring", "thinking": "All 8 accessible entrances operational. Elevators nominal.", "confidence": 92},
            "energy":        {"status": "monitoring", "thinking": "Power draw at 2.1 MW. Within baseline. Solar contributing 0.3 MW.", "confidence": 88},
            "volunteer":     {"status": "monitoring", "thinking": "217 volunteers checked in and at posts. Coverage 98%.", "confidence": 86},
            "food":          {"status": "monitoring", "thinking": "All 42 food concessions stocked. Queues empty.", "confidence": 83},
            "language":      {"status": "monitoring", "thinking": "PA system online. 11 language modules loaded and tested.", "confidence": 90},
            "risk":          {"status": "monitoring", "thinking": "Risk level 15/100. All subsystems green. No action required.", "confidence": 78},
            "executive":     {"status": "monitoring", "thinking": "AEGIS OS fully operational. Match day operations nominal.", "confidence": 85},
        },
        "scorecards": {
            "crowd_safety": 96,
            "transportation": 88,
            "medical_readiness": 94,
            "accessibility": 92,
            "energy_efficiency": 87,
            "overall": 91,
        },
        "metrics": {
            "occupancy": 74832,
            "temperature": 39,
            "energy_mw": 2.1,
            "volunteers_deployed": 217,
            "medical_alerts": 0,
            "transport_delay_min": 0,
        },
        "recommendations": [
            {
                "id": "rec_001",
                "title": "Pre-position 4 volunteers at Gate B",
                "description": "Historical data shows Gate B peak at T+7 minutes. Proactive positioning advised.",
                "confidence": 78,
                "status": "pending",
                "agentId": "crowd",
                "evidence": ["Historical pattern from 3/4 prior matches", "Gate B capacity 20000"],
                "reasoning": "Preventive positioning reduces response time by 3 minutes.",
                "tradeoffs": ["Slightly reduces coverage at Gate C"],
                "prediction": "Reduces potential congestion by 22%",
                "expectedOutcome": "Smooth fan flow through peak ingress window",
                "sources": ["Historical Data", "IoT Sensors"],
                "alternativesRejected": ["Closing Gate B immediately", "Redirecting traffic to Gate A"],
                "whyNot": ["Closing Gate B triggers a backlog on the transit platform.", "Gate A is already at 84% load limit."],
            }
        ],
        "trigger_debate": False,
        "debate": None,
        "confidence_point": 72,
        "blackbox_entry": None,
        "success_metrics": None,
    },

    # ─────────────────────────────────────────────────────────────────────────
    # EVENT 2 — Crowd Surge Detected
    # ─────────────────────────────────────────────────────────────────────────
    {
        "time": 180,
        "id": "event_crowd_surge",
        "title": "Crowd Surge Detected",
        "description": "Gate B density rising rapidly. Metro Line 1 delivering high fan volume.",
        "type": "warning",
        "zone_densities": {
            "north_gate_a":   0.65,
            "south_gate_b":   0.72,
            "east_gate_c":    0.52,
            "west_gate_d":    0.34,
            "field_level":    0.68,
            "lower_bowl":     0.75,
            "upper_bowl":     0.55,
            "concourse_main": 0.60,
        },
        "zone_risks": {
            "north_gate_a":   "high",
            "south_gate_b":   "high",
            "east_gate_c":    "moderate",
            "west_gate_d":    "safe",
            "field_level":    "moderate",
            "lower_bowl":     "high",
            "upper_bowl":     "moderate",
            "concourse_main": "moderate",
        },
        "risk_level": 42,
        "agent_states": {
            "crowd":         {"status": "analyzing", "thinking": "Gate B density at 72% and rising. Rate +4.2%/min. Predicted 91% in 7 minutes.", "confidence": 81},
            "transport":     {"status": "analyzing", "thinking": "Metro Line 1 delivering +1200 fans/min to Gate B vicinity. Peak arrival in 8 minutes.", "confidence": 78},
            "security":      {"status": "monitoring", "thinking": "No security anomalies. Monitoring Gate B crowd behavior.", "confidence": 83},
            "medical":       {"status": "monitoring", "thinking": "Heat stress risk rising with density. Monitoring for incidents.", "confidence": 85},
            "accessibility": {"status": "monitoring", "thinking": "Accessible route at Gate B still clear. Monitoring.", "confidence": 88},
            "energy":        {"status": "monitoring", "thinking": "Energy draw 2.3 MW. Slight increase from HVAC load.", "confidence": 86},
            "volunteer":     {"status": "monitoring", "thinking": "6 volunteers within 200m of Gate B. On standby.", "confidence": 82},
            "food":          {"status": "monitoring", "thinking": "Gate B food queues beginning to form. 3 min wait.", "confidence": 79},
            "language":      {"status": "monitoring", "thinking": "PA broadcasting standard welcome messages.", "confidence": 90},
            "risk":          {"status": "analyzing", "thinking": "Risk elevated to 42/100. Gate B trajectory concerning. Alert raised.", "confidence": 76},
            "executive":     {"status": "monitoring", "thinking": "Monitoring crowd agent analysis. Preparing contingency if Gate B hits 80%.", "confidence": 80},
        },
        "scorecards": {
            "crowd_safety": 84,
            "transportation": 82,
            "medical_readiness": 91,
            "accessibility": 90,
            "energy_efficiency": 85,
            "overall": 86,
        },
        "metrics": {
            "occupancy": 76200,
            "temperature": 39,
            "energy_mw": 2.3,
            "volunteers_deployed": 219,
            "medical_alerts": 1,
            "transport_delay_min": 0,
        },
        "recommendations": [
            {
                "id": "rec_002",
                "title": "Increase volunteer presence at Gate B",
                "description": "Deploy 6 additional volunteers to Gate B to manage rising density before critical threshold.",
                "confidence": 81,
                "status": "pending",
                "agentId": "volunteer",
                "evidence": ["Gate B density 72% and rising", "6 volunteers available within 200m"],
                "reasoning": "Early deployment prevents escalation to critical state.",
                "tradeoffs": ["Reduces Zone E volunteer coverage temporarily"],
                "prediction": "Slows density increase rate by 30%",
                "expectedOutcome": "Buys 4-6 additional minutes before critical threshold",
                "sources": ["IoT Sensors", "GPS Tracker"],
                "alternativesRejected": ["Deploying security barriers", "Force routing all incoming vehicles away"],
                "whyNot": ["Barriers block the flow and increase safety hazard risk.", "Forced routing triggers severe vehicle blockages near transit loops."],
            }
        ],
        "trigger_debate": False,
        "debate": None,
        "confidence_point": 81,
        "blackbox_entry": {
            "type": "prediction",
            "title": "Gate B Surge Prediction",
            "details": "Gate B density at 72% predicted to reach 91% in 7 minutes based on Metro Line 1 arrival data.",
            "accuracy": None,
        },
        "success_metrics": None,
    },

    # ─────────────────────────────────────────────────────────────────────────
    # EVENT 3 — Gate B Critical / AI Debate Triggered
    # ─────────────────────────────────────────────────────────────────────────
    {
        "time": 360,
        "id": "event_gate_b_critical",
        "title": "Gate B Critical — AI Debate Triggered",
        "description": "Gate B reaches 91% capacity. Multi-agent debate protocol initiated for immediate response.",
        "type": "critical",
        "zone_densities": {
            "north_gate_a":   0.84,
            "south_gate_b":   0.91,
            "east_gate_c":    0.67,
            "west_gate_d":    0.41,
            "field_level":    0.78,
            "lower_bowl":     0.82,
            "upper_bowl":     0.65,
            "concourse_main": 0.74,
        },
        "zone_risks": {
            "north_gate_a":   "high",
            "south_gate_b":   "critical",
            "east_gate_c":    "moderate",
            "west_gate_d":    "safe",
            "field_level":    "high",
            "lower_bowl":     "high",
            "upper_bowl":     "moderate",
            "concourse_main": "high",
        },
        "risk_level": 67,
        "agent_states": {
            "crowd":         {"status": "warning",   "thinking": "CRITICAL: Gate B at 91%. Initiating multi-agent debate protocol.", "confidence": 94},
            "transport":     {"status": "warning",   "thinking": "Opposing Gate B closure. 4200 incoming fans would pile up outside.", "confidence": 89},
            "security":      {"status": "warning",   "thinking": "Recommending partial closure. Single-file maintains flow.", "confidence": 91},
            "medical":       {"status": "warning",   "thinking": "Heat + crowd density = elevated medical risk. Pre-positioning 3 medics.", "confidence": 86},
            "accessibility": {"status": "analyzing", "thinking": "Wheelchair users in Gate B: 3. Flagging accessible alternate route.", "confidence": 90},
            "energy":        {"status": "monitoring","thinking": "HVAC at capacity. Monitoring for additional load.", "confidence": 85},
            "volunteer":     {"status": "warning",   "thinking": "14 volunteers available. ETA to Gate B: 2.1 min. Gate D: 1.8 min.", "confidence": 88},
            "food":          {"status": "monitoring","thinking": "Zone B queues will increase 4-7 min if crowd redirects to Gate D.", "confidence": 78},
            "language":      {"status": "warning",   "thinking": "Broadcasting multilingual redirect in EN ES AR FR PT. Preparing PA system.", "confidence": 95},
            "risk":          {"status": "critical",  "thinking": "RISK LEVEL: 67/100. Multi-agent response activated. ETA to resolution: 9 min.", "confidence": 88},
            "executive":     {"status": "critical",  "thinking": "Synthesizing 4 agent arguments. Generating executive decision in 12 seconds.", "confidence": 97},
        },
        "scorecards": {
            "crowd_safety": 71,
            "transportation": 79,
            "medical_readiness": 88,
            "accessibility": 89,
            "energy_efficiency": 84,
            "overall": 82,
        },
        "metrics": {
            "occupancy": 78400,
            "temperature": 39,
            "energy_mw": 2.6,
            "volunteers_deployed": 220,
            "medical_alerts": 2,
            "transport_delay_min": 4,
        },
        "recommendations": [],
        "trigger_debate": True,
        "debate": {
            "topic": "Gate B Congestion — Immediate Response Required",
            "arguments": [
                {
                    "agentId": "crowd",
                    "agentName": "Crowd Agent",
                    "color": "#ff3366",
                    "position": "Close Gate B immediately",
                    "confidence": 94,
                    "reasoning": "Crowd density at Gate B exceeds critical structural safety thresholds (91%). Stampede likelihood rising.",
                    "evidence": "Gate B camera flow counting at 1.8 fans/sec, concourse sensors show blockages",
                    "risk": "Safety threat to ingress path, potential minor crowd crush",
                    "expectedBenefit": "-41% congestion spike on south sector within 4 min",
                },
                {
                    "agentId": "transport",
                    "agentName": "Transport Agent",
                    "color": "#ffb300",
                    "position": "Do NOT close Gate B",
                    "confidence": 89,
                    "reasoning": "Metro arrival waves cannot be diverted dynamically at the platform level. Closure leads to immediate exterior backup.",
                    "evidence": "GTFS transit feed indicates Line 1 wave delivering +4,200 fans in next 8 minutes",
                    "risk": "Crush hazard outside the turnstiles due to limited queuing space",
                    "expectedBenefit": "Avoids catastrophic exterior bottlenecking",
                },
                {
                    "agentId": "security",
                    "agentName": "Security Agent",
                    "color": "#00d4ff",
                    "position": "Partial closure — single-file entry",
                    "confidence": 91,
                    "reasoning": "Slowing down ingress via structured security lanes maintains minor forward flow while protecting ticketing gates.",
                    "evidence": "CCTV feed shows volunteer spacing lanes are clear and secure",
                    "risk": "Aggressive queue pushing if lanes are not actively managed by stewards",
                    "expectedBenefit": "Restricts inflow rate by 60% without full shutdown",
                },
                {
                    "agentId": "volunteer",
                    "agentName": "Volunteer Agent",
                    "color": "#00ffcc",
                    "position": "Deploy volunteers and redirect signage",
                    "confidence": 88,
                    "reasoning": "Active physical redirection is 89% effective at diverting non-ticket holders to the low-density Gate D.",
                    "evidence": "GPS tracking shows 14 reserve volunteers within 120m proximity of the Gate B plaza",
                    "risk": "Temporary reduction of volunteer coverage in East Concourse",
                    "expectedBenefit": "Redirects 30% of incoming fans to Gate D within 3 minutes",
                },
            ],
            "finalDecision": {
                "actions": [
                    "Open Gate D to full capacity immediately",
                    "Deploy 14 volunteers to Gate B to D corridor",
                    "Update 3 digital signage boards redirect to Gate D",
                    "Delay Metro Line 1 Gate B exit by 4 minutes",
                    "Activate single-file entry at Gate B",
                ],
                "confidence": 97,
                "reasoning": "Combination approach balances immediate safety with transport reality. Gate D has 59% spare capacity. Volunteer corridor guidance proven 89% effective.",
                "expectedOutcome": "Gate B density reduces from 91% to 58% within 9 minutes. Zero incident probability rises to 94%.",
            },
        },
        "confidence_point": 97,
        "blackbox_entry": {
            "type": "action",
            "title": "Debate Protocol Activated",
            "details": "4 agents debating Gate B response strategy. Topics: immediate closure vs partial vs redirection.",
            "accuracy": None,
        },
        "success_metrics": None,
    },

    # ─────────────────────────────────────────────────────────────────────────
    # EVENT 4 — Executive Decision Executing
    # ─────────────────────────────────────────────────────────────────────────
    {
        "time": 540,
        "id": "event_actions_executing",
        "title": "Executive Decision Executing",
        "description": "All 5 executive actions are in motion. Gate B density beginning to drop.",
        "type": "action",
        "zone_densities": {
            "north_gate_a":   0.80,
            "south_gate_b":   0.85,
            "east_gate_c":    0.67,
            "west_gate_d":    0.55,
            "field_level":    0.80,
            "lower_bowl":     0.85,
            "upper_bowl":     0.68,
            "concourse_main": 0.70,
        },
        "zone_risks": {
            "north_gate_a":   "high",
            "south_gate_b":   "high",
            "east_gate_c":    "moderate",
            "west_gate_d":    "moderate",
            "field_level":    "high",
            "lower_bowl":     "high",
            "upper_bowl":     "moderate",
            "concourse_main": "high",
        },
        "risk_level": 48,
        "agent_states": {
            "crowd":         {"status": "monitoring", "thinking": "Gate B density 85% and decreasing. Volunteer corridor operational. Prediction 58% in 4 minutes.", "confidence": 96},
            "transport":     {"status": "monitoring", "thinking": "Metro Line 1 delay confirmed. 4 min delay implemented. Crowd buildup prevented.", "confidence": 91},
            "security":      {"status": "monitoring", "thinking": "Single-file entry at Gate B active. Flow rate 800/min. No incidents.", "confidence": 90},
            "medical":       {"status": "monitoring", "thinking": "3 medics pre-positioned. No heat incidents so far.", "confidence": 89},
            "accessibility": {"status": "monitoring", "thinking": "Wheelchair users successfully rerouted to Gate D accessible lane.", "confidence": 92},
            "energy":        {"status": "monitoring", "thinking": "Energy stable at 2.7 MW. HVAC maintaining 24C indoor temperature.", "confidence": 86},
            "volunteer":     {"status": "monitoring", "thinking": "14 volunteers active in corridor. Average redirect rate 340 fans/min.", "confidence": 91},
            "food":          {"status": "monitoring", "thinking": "Gate D food kiosks opening. Estimated 5 min queue at peak.", "confidence": 80},
            "language":      {"status": "monitoring", "thinking": "Gate D redirect announcement playing every 90 seconds in 5 languages.", "confidence": 93},
            "risk":          {"status": "monitoring", "thinking": "Risk dropping: 67 to 48. All actions on track. ETA green: 4 minutes.", "confidence": 88},
            "executive":     {"status": "monitoring", "thinking": "5 actions executing. Gate B tracking toward 58% target. On schedule.", "confidence": 95},
        },
        "scorecards": {
            "crowd_safety": 83,
            "transportation": 84,
            "medical_readiness": 90,
            "accessibility": 93,
            "energy_efficiency": 85,
            "overall": 87,
        },
        "metrics": {
            "occupancy": 79200,
            "temperature": 39,
            "energy_mw": 2.7,
            "volunteers_deployed": 234,
            "medical_alerts": 2,
            "transport_delay_min": 4,
        },
        "recommendations": [
            {
                "id": "rec_003",
                "title": "Monitor Gate D capacity",
                "description": "Gate D filling from 41% to 55% as redirect kicks in. Monitor 75% threshold.",
                "confidence": 88,
                "status": "pending",
                "agentId": "crowd",
                "evidence": ["Gate D 41% to 55% in 3 min", "Redirect still active"],
                "reasoning": "Preventive monitoring ensures Gate D does not become the new bottleneck.",
                "tradeoffs": [],
                "prediction": "Gate D safe at current rate — peak at 68% within safe limits",
                "expectedOutcome": "Peak at 68% within safe limits",
                "sources": ["IoT"],
                "alternativesRejected": ["Stop Gate D redirection flow", "Re-route to Gate C"],
                "whyNot": ["Redirection still required as Gate B density is at 85%.", "Gate C already showing moderate load and holds longer queue lines."],
            }
        ],
        "trigger_debate": False,
        "debate": None,
        "confidence_point": 96,
        "blackbox_entry": {
            "type": "action",
            "title": "Executive Decision Executed",
            "details": "5 actions initiated: Gate D opened, 14 volunteers deployed, signage updated, Metro delayed, single-file entry activated.",
            "accuracy": None,
        },
        "success_metrics": None,
    },

    # ─────────────────────────────────────────────────────────────────────────
    # EVENT 5 — Gate B Congestion Resolved
    # ─────────────────────────────────────────────────────────────────────────
    {
        "time": 720,
        "id": "event_gate_b_resolved",
        "title": "Gate B Congestion Resolved",
        "description": "Gate B drops from 91% to 58% in 8 minutes. All 5 actions succeeded. Black Box updated.",
        "type": "outcome",
        "zone_densities": {
            "north_gate_a":   0.72,
            "south_gate_b":   0.58,
            "east_gate_c":    0.62,
            "west_gate_d":    0.68,
            "field_level":    0.85,
            "lower_bowl":     0.90,
            "upper_bowl":     0.78,
            "concourse_main": 0.65,
        },
        "zone_risks": {
            "north_gate_a":   "high",
            "south_gate_b":   "moderate",
            "east_gate_c":    "moderate",
            "west_gate_d":    "moderate",
            "field_level":    "high",
            "lower_bowl":     "high",
            "upper_bowl":     "high",
            "concourse_main": "moderate",
        },
        "risk_level": 28,
        "agent_states": {
            "crowd":         {"status": "monitoring", "thinking": "Gate B: 91% to 58%. Target achieved. Prediction accuracy: 94.3% (based on 142 simulated data vectors). All zones monitoring.", "confidence": 94},
            "transport":     {"status": "monitoring", "thinking": "Metro delay lifted. Normal service resumed. All lines on schedule.", "confidence": 91},
            "security":      {"status": "monitoring", "thinking": "Single-file lifted at Gate B. Full flow resumed. All gates nominal.", "confidence": 90},
            "medical":       {"status": "monitoring", "thinking": "Medical alert cleared. All stations on standby.", "confidence": 93},
            "accessibility": {"status": "monitoring", "thinking": "All accessible routes fully operational across 8 gates.", "confidence": 96},
            "energy":        {"status": "monitoring", "thinking": "Energy optimized to 2.4 MW post-peak. 0.3 MW recovered.", "confidence": 88},
            "volunteer":     {"status": "monitoring", "thinking": "Volunteers returning to home positions. Gate D still supported.", "confidence": 91},
            "food":          {"status": "monitoring", "thinking": "Food queues normalizing. Gate D kiosks handling extra load well.", "confidence": 82},
            "language":      {"status": "monitoring", "thinking": "PA announcements returning to match day standard broadcasts.", "confidence": 92},
            "risk":          {"status": "monitoring", "thinking": "Risk: 28/100. Incident resolved. Black Box entry logged.", "confidence": 90},
            "executive":     {"status": "monitoring", "thinking": "SUCCESS: Gate B resolved in 8 min. Predicted 9 min. All 5 actions successful. Black Box updated.", "confidence": 94},
        },
        "scorecards": {
            "crowd_safety": 94,
            "transportation": 89,
            "medical_readiness": 93,
            "accessibility": 96,
            "energy_efficiency": 88,
            "overall": 92,
        },
        "metrics": {
            "occupancy": 80100,
            "temperature": 38,
            "energy_mw": 2.4,
            "volunteers_deployed": 220,
            "medical_alerts": 0,
            "transport_delay_min": 0,
        },
        "recommendations": [
            {
                "id": "rec_004",
                "title": "Maintain current configuration",
                "description": "Gate D remains open. Current zone balance is optimal. No changes needed.",
                "confidence": 94,
                "status": "pending",
                "agentId": "executive",
                "evidence": ["Gate B 58% safe", "Gate D 68% safe", "All zones normal"],
                "reasoning": "Configuration working well. Disrupting it may cause secondary imbalance.",
                "tradeoffs": [],
                "prediction": "Stable for next 12 minutes",
                "expectedOutcome": "Normal match operations",
                "sources": ["IoT", "Historical"],
                "alternativesRejected": ["Closing Gate D immediately", "Resetting Metro delays"],
                "whyNot": ["Redirection still clearing residual queues.", "Resetting Metro delays early runs risk of platform wave overlap."],
            }
        ],
        "trigger_debate": False,
        "debate": None,
        "confidence_point": 94,
        "blackbox_entry": {
            "type": "outcome",
            "title": "Gate B Incident Resolved",
            "details": "Density 91% to 58%. Time 8 min. Predicted 9 min. Accuracy 94.3% (based on 142 simulated data vectors).",
            "accuracy": 94,
        },
        "success_metrics": {
            "before": "Gate B: 91%",
            "after": "Gate B: 58%",
            "time_min": 8,
            "prediction_accuracy": 94,
            "fan_satisfaction_delta": 12,
            "medical_risk_delta": -28,
        },
    },

    # ─────────────────────────────────────────────────────────────────────────
    # EVENT 6 — Weather Alert — Storm Incoming
    # ─────────────────────────────────────────────────────────────────────────
    {
        "time": 960,
        "id": "event_weather_alert",
        "title": "Weather Alert — Storm Incoming",
        "description": "Meteorological sensors detect heavy rain approaching. ETA 12 minutes. Multi-agent planning activated.",
        "type": "warning",
        "zone_densities": {
            "north_gate_a":   0.65,
            "south_gate_b":   0.52,
            "east_gate_c":    0.58,
            "west_gate_d":    0.62,
            "field_level":    0.88,
            "lower_bowl":     0.91,
            "upper_bowl":     0.80,
            "concourse_main": 0.62,
        },
        "zone_risks": {
            "north_gate_a":   "moderate",
            "south_gate_b":   "moderate",
            "east_gate_c":    "moderate",
            "west_gate_d":    "moderate",
            "field_level":    "high",
            "lower_bowl":     "high",
            "upper_bowl":     "high",
            "concourse_main": "moderate",
        },
        "risk_level": 52,
        "agent_states": {
            "crowd":         {"status": "predicting", "thinking": "Rain arrival in 12 min. Outdoor zones will experience rapid density increase as fans seek shelter.", "confidence": 88},
            "transport":     {"status": "predicting", "thinking": "Weather alert. Predicting early exit requests. Metro capacity planning activated.", "confidence": 85},
            "security":      {"status": "monitoring", "thinking": "Storm protocol standby. Monitoring for crowd panic indicators.", "confidence": 84},
            "medical":       {"status": "predicting", "thinking": "Rain + 39C heat = rapid temperature drop risk. Hypothermia and slip-fall risk rising.", "confidence": 87},
            "accessibility": {"status": "monitoring", "thinking": "Identifying all covered accessible routes. Pre-clearing shelter paths.", "confidence": 88},
            "energy":        {"status": "predicting", "thinking": "Storm will trigger HVAC demand spike. Pre-loading battery reserves now.", "confidence": 85},
            "volunteer":     {"status": "predicting", "thinking": "Briefing 67 reserve volunteers for storm deployment. ETA to posts: 3 min.", "confidence": 83},
            "food":          {"status": "predicting", "thinking": "Indoor food demand will spike +68% within 8 min of rain. Alerting restocking team.", "confidence": 79},
            "language":      {"status": "predicting", "thinking": "Preparing storm guidance scripts in 11 languages. PA and app notifications ready.", "confidence": 93},
            "risk":          {"status": "analyzing", "thinking": "Risk 52/100. Weather cascading across all subsystems. Multi-agent response in 3 minutes.", "confidence": 86},
            "executive":     {"status": "analyzing", "thinking": "Storm scenario activating. Pre-computing response plan. Awaiting sensor confirmation.", "confidence": 88},
        },
        "scorecards": {
            "crowd_safety": 82,
            "transportation": 79,
            "medical_readiness": 85,
            "accessibility": 88,
            "energy_efficiency": 83,
            "overall": 83,
        },
        "metrics": {
            "occupancy": 80500,
            "temperature": 37,
            "energy_mw": 2.5,
            "volunteers_deployed": 220,
            "medical_alerts": 1,
            "transport_delay_min": 0,
        },
        "recommendations": [
            {
                "id": "rec_005",
                "title": "Open rain shelters immediately",
                "description": "Activate 8 covered concourse areas before rain hits to allow orderly fan movement.",
                "confidence": 91,
                "status": "pending",
                "agentId": "executive",
                "evidence": ["Rain ETA 12 min", "Covered capacity 22000 fans"],
                "reasoning": "Proactive shelter activation reduces panic when rain arrives.",
                "tradeoffs": ["Concourse density will temporarily increase"],
                "prediction": "Orderly shelter achieved in 8 minutes",
                "expectedOutcome": "No wet-weather incidents",
                "sources": ["Weather API", "IoT"],
                "alternativesRejected": ["Opening outer perimeter gates for early exit", "Deploying plastic coverings to seats"],
                "whyNot": ["Opening gates forces fans out into active lightning cells.", "Logistics of covering 80k seats in 12 min is impossible."],
            }
        ],
        "trigger_debate": False,
        "debate": None,
        "confidence_point": 88,
        "blackbox_entry": {
            "type": "prediction",
            "title": "Storm Impact Prediction",
            "details": "Heavy rain in 12 min. Predicting crowd behavioral shift, transport demand spike, and medical risk increase.",
            "accuracy": None,
        },
        "success_metrics": None,
    },

    # ─────────────────────────────────────────────────────────────────────────
    # EVENT 7 — Storm Hits — Multi-System Response
    # ─────────────────────────────────────────────────────────────────────────
    {
        "time": 1140,
        "id": "event_storm_hits",
        "title": "Storm Hits — Multi-System Response",
        "description": "Heavy rain arrives. Concourse and lower bowl reach critical density. 7-action executive response executing.",
        "type": "critical",
        "zone_densities": {
            "north_gate_a":   0.45,
            "south_gate_b":   0.38,
            "east_gate_c":    0.42,
            "west_gate_d":    0.48,
            "field_level":    0.78,
            "lower_bowl":     0.95,
            "upper_bowl":     0.88,
            "concourse_main": 0.91,
        },
        "zone_risks": {
            "north_gate_a":   "moderate",
            "south_gate_b":   "safe",
            "east_gate_c":    "moderate",
            "west_gate_d":    "moderate",
            "field_level":    "high",
            "lower_bowl":     "critical",
            "upper_bowl":     "high",
            "concourse_main": "critical",
        },
        "risk_level": 74,
        "agent_states": {
            "crowd":         {"status": "critical",  "thinking": "Concourse density: 91% CRITICAL. Lower bowl: 95% CRITICAL. 8 zones shifting simultaneously.", "confidence": 91},
            "transport":     {"status": "critical",  "thinking": "Metro demand +340%. Activating emergency protocol. 6 additional trains being dispatched.", "confidence": 88},
            "security":      {"status": "critical",  "thinking": "Elevated security protocol active. 847 personnel alerted. Monitoring for crowd panic.", "confidence": 85},
            "medical":       {"status": "critical",  "thinking": "3 medical alerts: 2 slip-falls, 1 heat plus rain exposure. 8 medics dispatching.", "confidence": 92},
            "accessibility": {"status": "critical",  "thinking": "Wet surfaces: wheelchair brake slip risk. Emergency accessible shelters opening.", "confidence": 89},
            "energy":        {"status": "critical",  "thinking": "HVAC boosted 35%. Current draw 3.1 MW. Activating battery reserves.", "confidence": 90},
            "volunteer":     {"status": "critical",  "thinking": "23 reserve volunteers deployed to concourse. Coverage 94% of critical zones.", "confidence": 87},
            "food":          {"status": "critical",  "thinking": "Indoor food demand +68%. Emergency restocking from warehouse. 15 min ETA.", "confidence": 78},
            "language":      {"status": "critical",  "thinking": "Storm guidance broadcast 11 languages. PA, screens, app, WhatsApp alerts active.", "confidence": 95},
            "risk":          {"status": "critical",  "thinking": "RISK: 74/100. Storm cascade active. 7 actions executing. ETA stable: 11 min.", "confidence": 89},
            "executive":     {"status": "critical",  "thinking": "7-action storm response executing. All agents coordinated. Monitoring every 30 seconds.", "confidence": 94},
        },
        "scorecards": {
            "crowd_safety": 68,
            "transportation": 64,
            "medical_readiness": 79,
            "accessibility": 76,
            "energy_efficiency": 71,
            "overall": 72,
        },
        "metrics": {
            "occupancy": 80500,
            "temperature": 29,
            "energy_mw": 3.1,
            "volunteers_deployed": 243,
            "medical_alerts": 3,
            "transport_delay_min": 8,
        },
        "recommendations": [],
        "trigger_debate": True,
        "debate": {
            "topic": "Storm Response — Multi-System Coordination Required",
            "arguments": [
                {
                    "agentId": "medical",
                    "agentName": "Medical Agent",
                    "color": "#ff6b35",
                    "position": "Immediate medic deployment to all outdoor areas",
                    "confidence": 92,
                    "reasoning": "Slip-fall incidents rising exponentially on wet pedestrian ramps. High probability of fracture incidents if unmitigated.",
                    "evidence": "3 medical alerts registered in last 60 seconds from Zone B and C ramps",
                    "risk": "Triage delays for head injuries, potential emergency services bottleneck",
                    "expectedBenefit": "Reduces field rescue response time from 6 min to under 2 min",
                },
                {
                    "agentId": "transport",
                    "agentName": "Transport Agent",
                    "color": "#ffb300",
                    "position": "Activate emergency transport protocol — extra Metro runs",
                    "confidence": 88,
                    "reasoning": "Rain surge triggers early stadium departure waves. Station platform holding space is insufficient.",
                    "evidence": "RFID gate exit logs show +340% increase in early egress traffic",
                    "risk": "Pedestrian crush hazard at platform escalators and gates",
                    "expectedBenefit": "Clears platform accumulation in under 90-second intervals",
                },
                {
                    "agentId": "energy",
                    "agentName": "Energy Agent",
                    "color": "#10b981",
                    "position": "Boost HVAC heating load in concourses immediately",
                    "confidence": 90,
                    "reasoning": "Wet fans transitioning to indoor zones run severe thermal shock hazard. Ambient concourse temperature must be stabilized.",
                    "evidence": "Indoor temperature drops 10°C in 4 min under draft conditions",
                    "risk": "Elevated hypothermia indicators among child and elderly demographics",
                    "expectedBenefit": "Restores thermal comfort baseline in 6 minutes",
                },
                {
                    "agentId": "volunteer",
                    "agentName": "Volunteer Agent",
                    "color": "#06b6d4",
                    "position": "Deploy all 67 reserve volunteers to concourse management",
                    "confidence": 87,
                    "reasoning": "Crowds seeking shelter are bottlenecking at level entryways. Guided corridor zoning prevents push surges.",
                    "evidence": "GPS registry shows 67 stewards standby at central locker room ready for immediate dispatch",
                    "risk": "Concourse entrances reach 95% threshold leading to local gridlock",
                    "expectedBenefit": "Orderly queue segregation within 3 minutes",
                },
            ],
            "finalDecision": {
                "actions": [
                    "Deploy 8 medics to outdoor zones immediately",
                    "Activate 6 emergency Metro trains at 90-second intervals",
                    "Boost HVAC by 35% across all indoor areas",
                    "Deploy 23 volunteers to concourse crowd management",
                    "Open emergency shelter zones Levels 2 and 3",
                    "Broadcast multilingual storm guidance on all PA systems",
                    "Notify 847 security personnel of elevated protocol",
                ],
                "confidence": 94,
                "reasoning": "Storm requires simultaneous multi-system activation. Medical, transport, and shelter are the three critical vectors. Volunteer deployment prevents concourse incidents.",
                "expectedOutcome": "All fans sheltered within 11 minutes. Max transport wait 8 minutes. Zero serious injuries.",
            },
        },
        "confidence_point": 94,
        "blackbox_entry": {
            "type": "action",
            "title": "Storm Response Activated",
            "details": "7 simultaneous actions across all subsystems: medical, transport, energy, volunteers, shelter, PA, security.",
            "accuracy": None,
        },
        "success_metrics": None,
    },

    # ─────────────────────────────────────────────────────────────────────────
    # EVENT 8 — Storm Stabilizing
    # ─────────────────────────────────────────────────────────────────────────
    {
        "time": 1440,
        "id": "event_storm_resolving",
        "title": "Storm Stabilizing — Situation Under Control",
        "description": "Outdoor zones clearing. All fans sheltered. 3 minor incidents treated. Emergency transport running.",
        "type": "outcome",
        "zone_densities": {
            "north_gate_a":   0.40,
            "south_gate_b":   0.35,
            "east_gate_c":    0.38,
            "west_gate_d":    0.42,
            "field_level":    0.78,
            "lower_bowl":     0.82,
            "upper_bowl":     0.75,
            "concourse_main": 0.72,
        },
        "zone_risks": {
            "north_gate_a":   "safe",
            "south_gate_b":   "safe",
            "east_gate_c":    "safe",
            "west_gate_d":    "moderate",
            "field_level":    "high",
            "lower_bowl":     "high",
            "upper_bowl":     "high",
            "concourse_main": "high",
        },
        "risk_level": 38,
        "agent_states": {
            "crowd":         {"status": "monitoring", "thinking": "Crowd distribution stabilizing. Outdoor zones clearing. Indoor zones at safe capacity.", "confidence": 93},
            "transport":     {"status": "monitoring", "thinking": "Emergency Metro running. Max wait time 6 min. Normal capacity restored in 8 min.", "confidence": 90},
            "security":      {"status": "monitoring", "thinking": "No security incidents. Storm crowd managed without panic. Elevated protocol downgraded.", "confidence": 88},
            "medical":       {"status": "monitoring", "thinking": "3 incidents: 2 slip-falls minor, 1 rain exposure. All treated. No hospitalizations.", "confidence": 93},
            "accessibility": {"status": "monitoring", "thinking": "All wheelchair users safely sheltered. Emergency accessible routes clear.", "confidence": 94},
            "energy":        {"status": "monitoring", "thinking": "HVAC sustaining 3.0 MW. Indoor temps stabilized at 22C. Battery reserves 60%.", "confidence": 87},
            "volunteer":     {"status": "monitoring", "thinking": "23 volunteers holding concourse positions. Situation stable.", "confidence": 89},
            "food":          {"status": "monitoring", "thinking": "Emergency restocking arrived. Indoor food queues at 8 min. Manageable.", "confidence": 81},
            "language":      {"status": "monitoring", "thinking": "Storm guidance replaced with comfort messages in 11 languages.", "confidence": 92},
            "risk":          {"status": "monitoring", "thinking": "Risk: 38/100 and dropping. Storm response successful. Black Box entry logged.", "confidence": 88},
            "executive":     {"status": "monitoring", "thinking": "Storm response successful. 80500 fans safe. 3 medical incidents managed. Zero serious injuries.", "confidence": 95},
        },
        "scorecards": {
            "crowd_safety": 87,
            "transportation": 81,
            "medical_readiness": 92,
            "accessibility": 94,
            "energy_efficiency": 84,
            "overall": 88,
        },
        "metrics": {
            "occupancy": 80500,
            "temperature": 28,
            "energy_mw": 3.0,
            "volunteers_deployed": 243,
            "medical_alerts": 0,
            "transport_delay_min": 6,
        },
        "recommendations": [
            {
                "id": "rec_007",
                "title": "Begin post-storm transport planning",
                "description": "80500 fans will exit simultaneously at match end. Peak in approximately 28 minutes.",
                "confidence": 89,
                "status": "pending",
                "agentId": "transport",
                "evidence": ["Match time remaining approx 28 min", "Historical exit surge +180%"],
                "reasoning": "Early transport coordination prevents post-match chaos.",
                "tradeoffs": ["Requires 12 min activation lead time"],
                "prediction": "Max Metro wait 14 min at peak",
                "expectedOutcome": "Safe orderly exit within 45 minutes",
                "sources": ["Transport API", "Historical"],
                "alternativesRejected": ["Immediate stadium evacuation", "Diverting all fans to parking lots"],
                "whyNot": ["Sudden evacuation risks crush stampedes at exits.", "Parking lot gates are currently flooded by local rain runoffs."],
            }
        ],
        "trigger_debate": False,
        "debate": None,
        "confidence_point": 95,
        "blackbox_entry": {
            "type": "outcome",
            "title": "Storm Response Complete",
            "details": "80500 fans safe. 3 minor medical incidents. Max crowd wait 8 min. All actions successful. Zero serious injuries.",
            "accuracy": 94,
        },
        "success_metrics": None,
    },

    # ─────────────────────────────────────────────────────────────────────────
    # EVENT 9 — Final Whistle — Match Complete
    # ─────────────────────────────────────────────────────────────────────────
    {
        "time": 1800,
        "id": "event_match_end",
        "title": "Final Whistle — Match Complete",
        "description": "Match concludes. 80500 fans exiting safely. Executive report being generated.",
        "type": "info",
        "zone_densities": {
            "north_gate_a":   0.20,
            "south_gate_b":   0.18,
            "east_gate_c":    0.22,
            "west_gate_d":    0.25,
            "field_level":    0.15,
            "lower_bowl":     0.30,
            "upper_bowl":     0.28,
            "concourse_main": 0.45,
        },
        "zone_risks": {
            "north_gate_a":   "safe",
            "south_gate_b":   "safe",
            "east_gate_c":    "safe",
            "west_gate_d":    "safe",
            "field_level":    "safe",
            "lower_bowl":     "safe",
            "upper_bowl":     "safe",
            "concourse_main": "moderate",
        },
        "risk_level": 12,
        "agent_states": {
            "crowd":         {"status": "monitoring", "thinking": "Exit flow nominal. All zones below 50%. Orderly dispersal confirmed.", "confidence": 95},
            "transport":     {"status": "monitoring", "thinking": "Post-match Metro running at full capacity. Max wait 11 min. On target.", "confidence": 90},
            "security":      {"status": "monitoring", "thinking": "Post-match sweep complete. No incidents. All exits clear.", "confidence": 92},
            "medical":       {"status": "monitoring", "thinking": "All stations on standby for post-match. No new alerts. Match complete.", "confidence": 95},
            "accessibility": {"status": "monitoring", "thinking": "All accessible exits operational. Smooth exit for mobility-assisted fans.", "confidence": 97},
            "energy":        {"status": "monitoring", "thinking": "Power draw reducing. Lights dimming in exited zones. Saving 0.4 MW.", "confidence": 90},
            "volunteer":     {"status": "monitoring", "thinking": "284 volunteers assisting exit flow. Excellent performance all day.", "confidence": 93},
            "food":          {"status": "monitoring", "thinking": "Concessions closing. Food waste 8.2%. Below 10% target. Success.", "confidence": 86},
            "language":      {"status": "monitoring", "thinking": "Post-match announcements playing in 11 languages. Transport guidance active.", "confidence": 94},
            "risk":          {"status": "monitoring", "thinking": "Risk 12/100. Match complete. 2 major incidents prevented. 3 managed. Score 94/100.", "confidence": 94},
            "executive":     {"status": "monitoring", "thinking": "Generating AI Executive Report. Match summary, incident analysis, lessons learned — complete in 15 seconds.", "confidence": 97},
        },
        "scorecards": {
            "crowd_safety": 96,
            "transportation": 88,
            "medical_readiness": 97,
            "accessibility": 98,
            "energy_efficiency": 91,
            "overall": 94,
        },
        "metrics": {
            "occupancy": 12300,
            "temperature": 27,
            "energy_mw": 1.8,
            "volunteers_deployed": 284,
            "medical_alerts": 0,
            "transport_delay_min": 11,
        },
        "recommendations": [
            {
                "id": "rec_008",
                "title": "AEGIS Executive Report Ready",
                "description": "AI-generated match report with full incident analysis, prediction accuracy, and recommendations for next match.",
                "confidence": 97,
                "status": "done",
                "agentId": "executive",
                "evidence": ["Match duration 97 min", "2 major incidents prevented", "3 medical incidents managed"],
                "reasoning": "Full match data compiled. Report generated by Executive Agent.",
                "tradeoffs": [],
                "prediction": "N/A",
                "expectedOutcome": "Lessons learned for next match",
                "sources": ["Black Box", "All Agents"],
                "alternativesRejected": ["Manual post-match data collection", "Delaying report compilation"],
                "whyNot": ["Manual aggregation requires 24+ hours and is prone to record leaks.", "Immediate compilation preserves situational integrity for venue operators."],
            }
        ],
        "trigger_debate": False,
        "debate": None,
        "confidence_point": 97,
        "blackbox_entry": {
            "type": "outcome",
            "title": "Match Complete — Report Generated",
            "details": "AT&T Stadium, USA vs Mexico. 80500 fans. 2 incidents prevented. 3 managed. Overall safety score 94/100.",
            "accuracy": 96,
        },
        "success_metrics": None,
    },
]
